name: Build Launcher

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache Gradle Packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: "gradle"
    - name: Set Up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: "npm"
    - run: npm ci
    - run: npm run buildClient
    - run: npm run make
    - name: Upload Artifact
      uses: actions/upload-artifact@v2-preview
      with:
        name: Sol Client Setup.deb
        path: out/make/deb/x64/*.deb
  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache Gradle Packages
      uses: actions/cache@v2
      with:
        path: |
          %userprofile%\.gradle\caches
          %userprofile%\.gradle\wrapper
        key: "gradle"
    - name: Set Up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: "npm"
    - name: Remove incompatible packages
      run: npm r electron-installer-debian
    - run: npm ci
    - run: npm run buildClient
    - run: npm run make
    - name: Upload Artifact
      uses: actions/upload-artifact@v2-preview
      with:
        name: Sol Client Setup.exe
        path: out/make/squirrel.windows/x64/*.exe
